### PR TITLE
Zap inline objects from backtraces

### LINKED ISSUE #1069: Trim literal objects from backtraces
To avoid heavy serialisation https://github.com/r-lib/testthat/issues/1223#issuecomment-723650610

### PR DESCRIPTION
**Pull request by lionel-**
Closes #1069.
Closes r-lib/testthat#1223.

Inline objects are replaced by their pillar type sum:

```r
call <- expr(foo(!!(1:2)))
call_zap_inline(call)
#> foo(`<int>`)
```

### CODE REVIEW

**Review by gaborcsardi — APPROVED** [review]

File: R/call.R [hunk 1]
```diff
@@ -1050,3 +1050,24 @@ call_type <- function(x) {
...
+      }
+      x[[3]] <- call_zap_inline(x[[3]])
+    } else {
+      x[] <- map(x, call_zap_inline)
+    }
+    return(x)
+  }
+
+  if (is_symbol(x) || is_syntactic_literal(x)) {
+    x
```
Comment (hadley) [inline R/call.R:1068]: I find this slightly easier to understand, but it's not that important

```suggestion
    x
  } else if (is_symbol(x) || is_syntactic_literal(x)) {
    x
```

File: tests/testthat/test-trace.R [hunk 2]
```diff
@@ -659,3 +659,18 @@ test_that("can bind backtraces", {
...
+  skip_if_not_installed("base", "3.5.0")
+
+  local_options(
+    rlang_trace_format_srcrefs = FALSE
+  )
+  e <- environment()
+  f <- function(...) g()
+  g <- function() h()
+  h <- function() trace_back(e)
+  trace <- inject(f(!!list()))
```
Comment (hadley) [inline tests/testthat/test-trace.R:674]: Could also use `do.call()` here, since that's the most common way that users will create inlined objects.

File: tests/testthat/_snaps/cnd-entrace.md [hunk 3]
```diff
@@ -40,7 +40,7 @@
        12.     \-rlang:::c()
        13.       +-base::withCallingHandlers(...)
        14.       +-rlang::with_abort(f())
-       15.       | \-base::withCallingHandlers(...)
+       15.       | \-base::withCallingHandlers(expr, error = `<fn>`)
```
Comment (hadley) [inline tests/testthat/_snaps/cnd-entrace.md:43]: Again, not very important, but why does this change?

File: tests/testthat/test-trace.R (hunk 2 above)
Comment (hadley) [reply tests/testthat/test-trace.R:674]: Maybe something like along these lines:

``` r
e <- environment()
f <- function() do.call("g", list(1:1e6 + 1))
g <- function(...) h()
h <- function() rlang::trace_back(e)
lobstr::obj_size(f())
#> 8,014,888 B
```

<sup>Created on 2021-09-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

(But using something other than `obj_size()`)

Comment (hadley) [reply tests/testthat/test-trace.R:674]: Maybe 

```R
trace <- f()
trace$calls[[3]]
```

?

**Review by hadley — APPROVED** [review]

File: R/call.R (hunk 1 above)
Comment (lionel-) [reply R/call.R:1068]: The idea here is to keep the terminating and recursive branches separate.

File: tests/testthat/_snaps/cnd-entrace.md (hunk 3 above)
Comment (lionel-) [reply tests/testthat/_snaps/cnd-entrace.md:43]: The injected handler is now a symbol. This allows `as_label()` to keep the whole call instead of eliding.

File: tests/testthat/test-trace.R (hunk 2 above)
Comment (lionel-) [reply tests/testthat/test-trace.R:675]: Good idea, I've added a `do.call()` and size check in the test.
