### PR TITLE
Review display of chained errors

### LINKED ISSUE #851: Improve display of chained errors
```r
a <- function() b()
b <- function() c()
c <- function() abort("low-level")

f <- function() g()
g <- function() h()
h <- function() tryCatch(a(), error = function(err) abort("high-level", parent = err))

f()
#> Error: high-level
#> Call `rlang::last_error()` to see a backtrace.

last_error()
#> <error/rlang_error>
#> high-level
#> Backtrace:
#>  1. global::f()
#>  2. global::g()
#>  3. global::h()
#> Call `rlang::last_trace()` to see the full backtrace.

last_trace()
#> <error/rlang_error>
#> high-level
#> Backtrace:
#>     █
#>  1. └─global::f()
#>  2.   └─global::g()
#>  3.     └─global::h()
#> <parent: error/rlang_error>
#> low-level
#> Backtrace:
#>     █
#>  1. └─global::a()
#>  2.   └─global::b()
#>  3.     └─global::c()

last_error()$parent
#> <error/rlang_error>
#> low-level
#> Backtrace:
#>   1. global::f()
#>   2. global::g()
#>   3. global::h()
#>   8. global::a()
#>   9. global::b()
#>  10. global::c()

last_error()$parent$trace
#>      █
#>   1. └─global::f()
#>   2.   └─global::g()
#>   3.     └─global::h()
#>   4.       ├─base::tryCatch(...)
#>   5.       │ └─base:::tryCatchList(expr, classes, parentenv, handlers)
#>   6.       │   └─base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
#>   7.       │     └─base:::doTryCatch(return(expr), name, parentenv, handler)
#>   8.       └─global::a()
#>   9.         └─global::b()
#>  10.           └─global::c()
```

Comments from @gaborcsardi 

1. It would make sense to indicate in the default output that there is another level. Even the last_error() output does not indicate that, actually. You probably end up staring at the error for a bit and then calling last_error() as suggested, and then after some more staring last_trace(), as suggested. And you'd better not mistype either one, because then the last error object will be gone.

2. Having to call $parent to get a complete stack is not great, especially if you have more than two levels, i.e. last_error()$parent$parent, etc. The same with last_error()$parent$parent$trace, etc.

3. Having different numbers for the parent frames in last_trace() might be confusing. Personally I would prefer if the numbers were not mangled, and they referred to the real frame numbers.

4. There is no way to see all error messages and a full stack, in the same output. Personally, this is my preferred output, as above, as it shows all information, and the levels are clearly separated by whitespace, and they are easy to parse. I can decide how deep I need to dig into the output, without issuing additional commands.

5. Relatedly, I am not sure that having all these different kinds of output is great. People need to learn to parse all of them, and think about whether the information they are looking for is missing in general, or they need the other kind of output, etc.

### PR DESCRIPTION
**Pull request by lionel-**
* We now climb the ancestry of chained errors to find the oldest parent errors carrying a backtrace and display this backtrace in full. This is the oldest and thus most complete backtrace.

* We no longer decompose backtraces across error contexts because there is no way for us to do this with calling handlers. Calling handlers are now the preferred methods of rethrowing errors because they preserve the stack and allow users to `recover()` the error.

* The combination of these two changes produces consistent error and backtrace output for errors rethrown from both `tryCatch()` and `withCallingHandlers()`.

* The error ancestry is reflected with a tree display for error messages. The first message for the youngest error (highest level) is generated with `conditionMessage()`. The messages for older errors are generated with `cnd_header()`. This avoids repetition when the younger errors reuse parts of the messages of their parent errors, e.g. in bullets.

Closes #851

```r
dplyr::mutate(mtcars, dplyr::select(mtcars, foo))
#> Error: Problem with `mutate()` input `..1`.
#> ✖ Can't subset columns that don't exist.
#> ✖ Column `foo` doesn't exist.
#> ℹ Input `..1` is `dplyr::select(mtcars, foo)`.
#> Run `rlang::last_error()` to see where the error occurred.

rlang::last_error()
#> █
#> ├─<error/dplyr_error>
#> │ Problem with `mutate()` input `..1`.
#> │ ✖ Can't subset columns that don't exist.
#> │ ✖ Column `foo` doesn't exist.
#> │ ℹ Input `..1` is `dplyr::select(mtcars, foo)`.
#> └─<error/vctrs_error_subscript_oob>
#>   Can't subset columns that don't exist.
#> Backtrace:
#>   1. dplyr::mutate(mtcars, dplyr::select(mtcars, foo))
#>  10. dplyr:::select.data.frame(mtcars, foo)
#>  11. tidyselect::eval_select(expr(c(...)), .data)
#>  12. tidyselect:::eval_select_impl(...)
#>  20. tidyselect:::vars_select_eval(...)
#>  21. tidyselect:::walk_data_tree(expr, data_mask, context_mask)
#>  22. tidyselect:::eval_c(expr, data_mask, context_mask)
#>  23. tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
#>  24. tidyselect:::walk_data_tree(new, data_mask, context_mask)
#>  25. tidyselect:::as_indices_sel_impl(...)
#>  26. tidyselect:::as_indices_impl(x, vars, strict = strict)
#>  27. tidyselect:::chr_as_locations(x, vars)
#>  28. vctrs::vec_as_location(x, n = length(vars), names = vars)
#>  29. vctrs:::stop_subscript_oob(...)
#>  30. vctrs:::stop_subscript(...)
#> Run `rlang::last_trace()` to see the full context.

rlang::last_trace()
#> █
#> ├─<error/dplyr_error>
#> │ Problem with `mutate()` input `..1`.
#> │ ✖ Can't subset columns that don't exist.
#> │ ✖ Column `foo` doesn't exist.
#> │ ℹ Input `..1` is `dplyr::select(mtcars, foo)`.
#> └─<error/vctrs_error_subscript_oob>
#>   Can't subset columns that don't exist.
#> Backtrace:
#>      █
#>   1. ├─dplyr::mutate(mtcars, dplyr::select(mtcars, foo))
#>   2. ├─dplyr:::mutate.data.frame(mtcars, dplyr::select(mtcars, foo))
#>   3. │ └─dplyr:::mutate_cols(.data, ...)
#>   4. │   ├─base::tryCatch(...)
#>   5. │   │ └─base:::tryCatchList(expr, classes, parentenv, handlers)
#>   6. │   │   └─base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
#>   7. │   │     └─base:::doTryCatch(return(expr), name, parentenv, handler)
#>   8. │   └─mask$eval_all_mutate(dots[[i]])
#>   9. ├─dplyr::select(mtcars, foo)
#>  10. └─dplyr:::select.data.frame(mtcars, foo)
#>  11.   └─tidyselect::eval_select(expr(c(...)), .data)
#>  12.     └─tidyselect:::eval_select_impl(...)
#>  13.       ├─tidyselect:::with_subscript_errors(...)
#>  14.       │ ├─base::tryCatch(...)
#>  15.       │ │ └─base:::tryCatchList(expr, classes, parentenv, handlers)
#>  16.       │ │   └─base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
#>  17.       │ │     └─base:::doTryCatch(return(expr), name, parentenv, handler)
#>  18.       │ └─tidyselect:::instrument_base_errors(expr)
#>  19.       │   └─base::withCallingHandlers(...)
#>  20.       └─tidyselect:::vars_select_eval(...)
#>  21.         └─tidyselect:::walk_data_tree(expr, data_mask, context_mask)
#>  22.           └─tidyselect:::eval_c(expr, data_mask, context_mask)
#>  23.             └─tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
#>  24.               └─tidyselect:::walk_data_tree(new, data_mask, context_mask)
#>  25.                 └─tidyselect:::as_indices_sel_impl(...)
#>  26.                   └─tidyselect:::as_indices_impl(x, vars, strict = strict)
#>  27.                     └─tidyselect:::chr_as_locations(x, vars)
#>  28.                       └─vctrs::vec_as_location(x, n = length(vars), names = vars)
#>  29.                         └─vctrs:::stop_subscript_oob(...)
#>  30.                           └─vctrs:::stop_subscript(...)
```

### CODE REVIEW

File: R/cnd-error.R [hunk 1]
```diff
@@ -77,14 +118,55 @@ format.rlang_error <- function(x,
...
     reminder <- silver("Run `rlang::last_trace()` to see the full context.")
     out <- paste_line(out, reminder)
   }
 
   out
 }
 
+with_reduced_width <- function(expr) {
+  with_options(
+    width = peek_option("width") - 2L,
```
Comment (krlmlr) [inline R/cnd-error.R:131]:
```suggestion
    width = max(peek_option("width") - 2L, 10L)
```

File: R/utils.R [hunk 2]
```diff
@@ -254,3 +254,15 @@ unstructure <- function(x) {
...
+cli_rule <- function() {
+  if (is_installed("cli")) {
+    cli::rule()
+  } else {
+    strrep("-", peek_option("width") %||% 60L)
+  }
+}
+
+split_lines <- function(x) {
+  strsplit(x, "\n")[[1]]
```
Comment (krlmlr) [inline R/utils.R:267]:
```suggestion
  strsplit(x, "\n", fixed = TRUE)[[1]]
```
